target("socket_test")
    set_kind("binary")
    add_includedirs("../include/moshirpc/")
    add_files("socket_test.cpp")
    add_deps("network_module")

target("eventloop_test")
    set_kind("binary")
    add_includedirs("../include/moshirpc")
    add_files("eventloop_test.cpp")
    add_packages("gtest")
    add_links("gtest_main")
    add_deps("network_module")

target("buffer_test")
    set_kind("binary")
    add_includedirs("../include/moshirpc")
    add_files("buffer_test.cpp")
    add_packages("gtest")
    add_links("gtest_main")
    add_deps("common_module")

target("timer_test")
    set_kind("binary")
    add_includedirs("../include/moshirpc")
    add_files("timer_test.cpp")
    add_deps("common_module")
    add_packages("gtest")
    add_links("gtest_main")

target("threadpool_test")
    set_kind("binary")
    add_includedirs("../include/moshirpc")
    add_files("threadpool_test.cpp")
    -- Only for linking: use the existing implementation unit, but tests are designed
    -- strictly from the header contract.
    add_files("../src/common/thread_pool.cpp")
    add_packages("gtest")
    add_links("gtest_main")
