target("common")
    set_kind("static")
    add_files("*.cpp")
    add_includedirs(".", { public = true })

target("test_buffer")
    set_default(false)
    set_kind("binary")
    add_files("tests/test_buffer.cpp")
    add_includedirs(".")
    add_deps("common")
    add_packages("gtest")