target("protocol")
    set_kind("static")
    add_files("src/*.cpp")
    add_includedirs("include", { interface = true })
    add_packages("cjson")

target("proto_test")
    set_kind("binary")
    add_files("tests/proto_test.cpp")
    add_includedirs("include")
    add_packages("gtest")